In [1]:
import numpy as np


In [2]:
a=[1,2,3,4]

In [3]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2= np.arange(10,20,2.4)
arr2

array([10. , 12.4, 14.8, 17.2, 19.6])

In [6]:
arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr3.size

9

In [8]:
arr3.ndim

2

In [9]:
arr3.dtype

dtype('int32')

In [10]:
arr3.max()

9

In [11]:
arr3.min

<function ndarray.min>

In [12]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr3.prod()

362880

In [14]:
arr3.sum()

45

In [15]:
np.arange(1,9 ,dtype = np.float64).reshape(2,2,2)

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [16]:
mat1 = np.arange(1,21)

In [18]:
mat1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
b_array = mat1 % 2==0
b_array

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [20]:
mat1[b_array]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [21]:
mat1[mat1 %5==0]

array([ 5, 10, 15, 20])

In [23]:
mat1 = [2,4]

In [30]:
mat1 = np.arange(1,21).reshape(4,5)
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
mat1[0:2,1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [33]:
np.random.random((5,5))

array([[0.27111651, 0.81228689, 0.62301348, 0.42214406, 0.21677581],
       [0.22820237, 0.8207696 , 0.26988643, 0.09883376, 0.36025755],
       [0.4759119 , 0.02429999, 0.28980419, 0.79948058, 0.08879959],
       [0.78791401, 0.9478895 , 0.12871988, 0.26686848, 0.67248544],
       [0.39235765, 0.83839415, 0.75555956, 0.69959299, 0.86554982]])

In [37]:
np.random.randint(1,20,(10,10))

array([[15, 18,  4,  9,  7,  5, 11, 18,  5,  9],
       [ 3,  3,  4, 18,  8,  2, 12,  4, 11,  8],
       [ 5, 11,  9,  1, 10, 16, 16, 10, 15,  6],
       [ 5, 19,  6, 19,  8,  1, 12, 16, 15,  3],
       [13,  3,  5,  4,  8, 18,  7,  4, 15, 19],
       [17,  6,  9, 19,  8, 15,  9,  7,  3,  4],
       [ 2,  3,  6, 17, 10, 15,  4, 11,  3,  5],
       [18,  6, 15, 16, 14,  1,  6, 12,  4,  1],
       [19, 14,  7, 13,  8,  7,  8, 11, 15, 18],
       [ 6,  2,  6, 16,  2, 19,  8,  7, 10,  2]])